version: '3.8'
services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped