version: '3.8'
services:
  main-server:
    container_name: myhome-server
    image: minjee12/myhome:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env   # 서버에서 echo "${{ secrets.APPLICATION_ENV }}" > .env 한 파일
    networks:
      - shared-net

networks:
  shared-net:

