spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 집
    url: jdbc:mysql://localhost:3307/dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 11111111
    # 회사
#    url: jdbc:mysql://localhost:3306/db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
jwt:
  secret:
    key: ${JWT_SECRET}

public:
  api:
    key: ${PUBLIC_API_KEY}