name: CD 

on:
   # CI 워크플로우가 완료되었을 때만 실행
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # CI가 성공적으로 끝나면 실행
    
    permissions:
      contents: read
      packages: write
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # CI에서 업로드된 아티팩트(결과물)를 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-jar # CI에서 업로드한 아티팩트 이름과 동일하게 지정
          path: build/libs/ # 다운로드할 경로
          run-id: ${{ github.event.workflow_run.id }} 
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}


# -------------------- ▼▼▼ Docker 관련 로직 추가 ▼▼▼ --------------------

      # 1. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. JAR 파일 이름 변수 설정 (Dockerfile에 전달하기 위함)
      - name: Set JAR file name
        run: |
          JAR_FILE=$(find build/libs -name '*.jar' | head -n 1)
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV
        shell: bash

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Dockerfile 위치 (프로젝트 루트)
          file: ./Dockerfile # Dockerfile 이름
          push: true # 빌드 후 푸시 실행
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/our-home:latest # Docker 이미지 태그
          build-args: |
            JAR_FILE=${{ env.JAR_FILE }} # Dockerfile 내부에서 사용할 변수 전달

    # -------------------- ▼▼▼ SSH 원격 배포 로직 추가 ▼▼▼ --------------------

      # 4. SSH로 서버에 접속하여 배포 스크립트 실행
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }} # 서버 IP 주소
          username: ${{ secrets.SSH_USERNAME }} # 서버 접속 계정 (예: ubuntu, ec2-user)
          key: ${{ secrets.SSH_PRIVATE_KEY }} # SSH 접속을 위한 Private Key
          script: |
            # Docker Hub에서 최신 이미지를 pull 받습니다.
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/our-home:latest
            
            # 기존에 실행 중인 컨테이너가 있다면 중지하고 제거합니다. (없어도 오류가 발생하지 않습니다.)
            docker stop our-home-container || true
            docker rm our-home-container || true
            
            # 다운로드받은 최신 이미지로 새 컨테이너를 실행합니다.
            # 포트포워딩: -p [호스트 포트]:[컨테이너 포트]
            docker run -d --name our-home-container -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/our-home:latest

