name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    # env 값을 가져오기
    env:
      APPLICATION_ENV: "${{ secrets.APPLICATION_ENV }}"

    # 가져온 env값으로 새로운 env파일을 만들어서 사용하기
    steps:
    - uses: actions/checkout@v4
    - name: Create .env file from secret
      run: |
        echo "${{ secrets.APPLICATION_ENV }}" > .env
      shell: bash

  # 24버전 자바 세팅하기
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

  # 'gradle-build-action' 사용 대신, 직접 'gradlew' 스크립트 실행
    - name: Build with Gradle
      run: ./gradlew build -x test

      
    # 빌드된 jar 파일을 artifact로 업로드하는 단계
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-jar # artifact 이름
        path: build/libs/*.jar # 빌드된 jar 파일 경로
